### ISSUE TITLE
Actions to make use of the tox. 

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/actions#170]
To use tox in a GitHub Actions workflow for a project that is already configured with tox, we can modify existing actions or create a new action to integrate tox with the build and test process. 

Here are the advantages of this:

* we can make use of the requirements of choice in lib itself ( The dependency can be in toml or .txt format.)

* By using tox in the GitHub Actions workflow, we can verify that the package builds and installs correctly under different environments.

* We can also run additional modules before building using tox to ensure that the package is built correctly. ( eg: run a python module before building the docs)

* If we want to have custom Sphinx options in the lib itself, such as warnings or avoidance of warnings during the docs build, we can do so with tox.

Discussed in private with @jorgepiloto , Pinging here @RobPasMue , @MaxJPRey for suggestion.

**Comment by RobPasMue** [comment]
I think tox is a great tool for dev purposes (check local install, testing etc.) but in terms of CI/CD it has one major disadvantage, which is the fact that caching no longer works "out-of-the-box". And that makes sense, because it is the whole point of tox, to create a new env from a clean sheet...

* We are oushing towards moving requirements to pyproject.toml files. I think that we should keep pushing in that line rather than going back to requirements files... repos are much cleaner without them.
* You can achieve the same goal (different Python versions, different environments) with our current matrix strategies when running the wheelhouse so I don't see there is much change here.
* We are already doing smoke tests before building the docs so, again, no advantage on your third point.
* We can already define custom Sphinx options with our actions. And users can already define whatever flags they want to run their sphinx build directly with their Makefiles (or by passing them in). So again, no advantage.

I believe tox should remain as it is now, for developers to validate atomically. But I do think that our current GH Actions strategy is much more efficient (and as reliable as using tox).

**Comment by RobPasMue** [comment]
I propose closing this issue, but I am open to discussion. I don't believe that it will provide any advantage. I would by all means avoid modifying the existing actions, for sure. But if you really insist on creating new actions for tox purposes then be my guests... Don't get me wrong, I think tox is great. But I do think as well that it is going to be a toll in performance for our workflows without any real advantage.

**Comment by RobPasMue** [comment]
Hey, can we close this issue? @jorgepiloto @Revathyvenugopal162 @MaxJPRey

**Comment by jorgepiloto** [comment]
I agree, @RobPasMue. @Revathyvenugopal162 opened this originally after I suggested so. However, I think it is better for the actions to avoid tox. If actions were using tox, we would not be able to enforce the location of files like `requiremens/requirements_*.txt`, for example.
