### ISSUE TITLE
Remove branch-name-style in favor of branch rulesets

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/actions#575]
With GitHub rulesets, this action is no longer required. @SMoraisAnsys pointed out this.

**Comment by SMoraisAnsys** [comment]
Yeah. While I think that having a convention for branch naming is great, I also think that we shouldn't end up in a situation where after doing my changes and opening a PR, I have to create a new branch and a new PR because the current branch was not correct. It would have been better to not be able to push to the repo in the first place so that I could know that I should rename my branch.
